export const VALID_INSTITUTION_TYPES = ["school", "college", "university"] as const;
export type InstitutionType = typeof VALID_INSTITUTION_TYPES[number];

export interface InstitutionSeedEntry {
    name: string;
    type: InstitutionType;
    isActive: boolean;
}

export const institutionsSeedData: InstitutionSeedEntry[] = [
    // ── Universities ──────────────────────────────────────────────
    { name: "Tribhuvan University", type: "university", isActive: true },
    { name: "Kathmandu University", type: "university", isActive: true },
    { name: "Pokhara University", type: "university", isActive: true },
    { name: "Purbanchal University", type: "university", isActive: true },
    { name: "Mid-Western University", type: "university", isActive: true },
    { name: "Far-Western University", type: "university", isActive: true },
    { name: "Nepal Sanskrit University", type: "university", isActive: true },
    { name: "Agriculture and Forestry University", type: "university", isActive: true },
    { name: "Lumbini Buddhist University", type: "university", isActive: true },
    { name: "Rajarshi Janak University", type: "university", isActive: true },
    { name: "Nepal Open University", type: "university", isActive: true },
    { name: "Gandaki University", type: "university", isActive: true },
    { name: "National Academy of Medical Sciences", type: "university", isActive: true },

    // ── Colleges ──────────────────────────────────────────────────
    // Engineering
    { name: "Pulchowk Campus", type: "college", isActive: true },
    { name: "Thapathali Campus", type: "college", isActive: true },
    { name: "Nepal Engineering College", type: "college", isActive: true },
    { name: "Kantipur Engineering College", type: "college", isActive: true },
    { name: "Advanced College of Engineering and Management", type: "college", isActive: true },
    { name: "Himalaya College of Engineering", type: "college", isActive: true },
    { name: "Khwopa Engineering College", type: "college", isActive: true },
    { name: "National College of Engineering", type: "college", isActive: true },
    { name: "Sagarmatha Engineering College", type: "college", isActive: true },
    { name: "Kathmandu Engineering College", type: "college", isActive: true },
    { name: "Lalitpur Engineering College", type: "college", isActive: true },
    { name: "Lumbini Engineering College", type: "college", isActive: true },
    { name: "Chitwan Engineering College", type: "college", isActive: true },
    // IT / Computing
    { name: "Herald College Kathmandu", type: "college", isActive: true },
    { name: "Islington College", type: "college", isActive: true },
    { name: "Informatics College Pokhara", type: "college", isActive: true },
    { name: "NIST College", type: "college", isActive: true },
    { name: "Deerwalk Institute of Technology", type: "college", isActive: true },
    { name: "Softwarica College of IT and E-Commerce", type: "college", isActive: true },
    // Management / Business
    { name: "Shanker Dev Campus", type: "college", isActive: true },
    { name: "Little Angels College of Management", type: "college", isActive: true },
    { name: "Ace Institute of Management", type: "college", isActive: true },
    { name: "Nepal College of Management", type: "college", isActive: true },
    { name: "Kathmandu College of Management", type: "college", isActive: true },
    { name: "Uniglobe College", type: "college", isActive: true },
    { name: "Prime College", type: "college", isActive: true },
    { name: "Kathmandu University School of Management", type: "college", isActive: true },
    // Medical / Health
    { name: "KIST Medical College", type: "college", isActive: true },
    { name: "Manipal College of Medical Sciences", type: "college", isActive: true },
    { name: "Nepal Medical College", type: "college", isActive: true },
    { name: "B.P. Koirala Institute of Health Sciences", type: "college", isActive: true },
    { name: "Kathmandu Model Hospital College of Nursing", type: "college", isActive: true },
    // General / Liberal Arts
    { name: "St. Xavier's College Maitighar", type: "college", isActive: true },
    { name: "Tri-Chandra Multiple Campus", type: "college", isActive: true },
    { name: "Amrit Campus", type: "college", isActive: true },
    { name: "Patan Multiple Campus", type: "college", isActive: true },
    { name: "Padma Kanya Multiple Campus", type: "college", isActive: true },
    { name: "Bhaktapur Multiple Campus", type: "college", isActive: true },
    { name: "Prithvi Narayan Campus", type: "college", isActive: true },
    { name: "Mahendra Multiple Campus Dharan", type: "college", isActive: true },
    { name: "Birendra Multiple Campus Bharatpur", type: "college", isActive: true },
    { name: "Butwal Multiple Campus", type: "college", isActive: true },
    { name: "Siddhanath Multiple Campus Mahendranagar", type: "college", isActive: true },
    { name: "Dhankuta Multiple Campus", type: "college", isActive: true },
    { name: "Western Region Campus Pokhara", type: "college", isActive: true },

    // ── Schools ───────────────────────────────────────────────────
    { name: "Saint Xavier's School Jawalakhel", type: "school", isActive: true },
    { name: "Budhanilkantha School", type: "school", isActive: true },
    { name: "Rato Bangala School", type: "school", isActive: true },
    { name: "Galaxy Public School", type: "school", isActive: true },
    { name: "Kathmandu Model Secondary School", type: "school", isActive: true },
    { name: "Bal Mandir School", type: "school", isActive: true },
    { name: "Shuvatara School", type: "school", isActive: true },
    { name: "Lincoln School Kathmandu", type: "school", isActive: true },
    { name: "The British School Kathmandu", type: "school", isActive: true },
    { name: "Ullens School", type: "school", isActive: true },
    { name: "Pentagon International College", type: "school", isActive: true },
    { name: "Pokhara Higher Secondary School", type: "school", isActive: true },
    { name: "Gandaki Boarding School", type: "school", isActive: true },
    { name: "Biratnagar International School", type: "school", isActive: true },
    { name: "Birgunj Public School", type: "school", isActive: true },
    { name: "Little Angels' School", type: "school", isActive: true },
    { name: "GEMS School", type: "school", isActive: true },
    { name: "Premier International School", type: "school", isActive: true },
    { name: "Chelsea International Academy", type: "school", isActive: true },
    { name: "Pathshala Nepal Foundation", type: "school", isActive: true },
    { name: "Sanskriti International School", type: "school", isActive: true },
    { name: "Nepal Police School", type: "school", isActive: true },
    { name: "DAV Sushil Kedia Vishwa Bharati School", type: "school", isActive: true },
    { name: "KMC School", type: "school", isActive: true },
    { name: "KWS School", type: "school", isActive: true },
    { name: "Nightingale International Secondary School", type: "school", isActive: true },
    { name: "Graded English Medium School", type: "school", isActive: true },
    { name: "United Academy", type: "school", isActive: true },
    { name: "Xavier International School", type: "school", isActive: true },
    { name: "Trinity International College", type: "school", isActive: true },
    { name: "Global College International", type: "school", isActive: true },
    { name: "Kathmandu World School", type: "school", isActive: true },
    { name: "Euro School", type: "school", isActive: true },
    { name: "Brihaspati VidyaSadan", type: "school", isActive: true },
    { name: "Learning Realm International School", type: "school", isActive: true },
    { name: "Ideal Model School", type: "school", isActive: true },
    { name: "Nobel Academy", type: "school", isActive: true },
    { name: "New Summit School", type: "school", isActive: true },
    { name: "Everest English School", type: "school", isActive: true },
    { name: "Bagmati Boarding Secondary School", type: "school", isActive: true },
    { name: "Valley View English School", type: "school", isActive: true },
    { name: "Kavya School", type: "school", isActive: true },
    { name: "The Chandbagh School", type: "school", isActive: true },
    { name: "Malpi International School", type: "school", isActive: true },
    { name: "Sainik Awasiya Mahavidyalaya", type: "school", isActive: true },
    { name: "Siddhartha Vanasthali Institute", type: "school", isActive: true },
    { name: "Mills Berry School", type: "school", isActive: true },
    { name: "Aksharaa School", type: "school", isActive: true },
    { name: "Swostishree Gurukul", type: "school", isActive: true },
    { name: "Triyog High School", type: "school", isActive: true },
    { name: "Reliance International Academy", type: "school", isActive: true },
    { name: "Manaslu Public Secondary School", type: "school", isActive: true },
];